FROM python:3.10

RUN mkdir -p /app
WORKDIR /app

ENV PYTHONUNBUFFERED=1

COPY ./backend/requirements.txt /app/
RUN pip install -r requirements.txt

COPY ./backend /app/
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
